### ISSUE TITLE
Radiobutton not displaying

### ISSUE THREAD

**Issue by firstimpressionmusic** [farag2/Windows-10-Sophia-Script#159]
![save](https://user-images.githubusercontent.com/48518681/114296286-1f0cc780-9ac8-11eb-98fd-66eca76827be.png)

Radio button to save presets not displaying

**Comment by BenchTweakGaming** [comment]
Hi firstimpressionmusic,
The "Output Radiobuttons" and accompanying "Save", "Save As" was removed because now the wrapper can read from "Sophia.PS1" files now to populate the radiobuttons in each tab. 
I mean you can press "Output PowerShell" and "Save As" your choice of name for the PS1 file and open it up in the "Options" via "Open PS1". It should fully work now. This feature was in development for a while. You no longer need TXT preset files to separately save your choices or open them,
